[versions]
agp = "8.2.2"
appcompat = "1.6.1"
fragment = "1.6.2"
navigation = "2.7.7"
preference = "1.2.1"
shapes = "1.0.0-alpha05"
material = "1.12.0-alpha03"
wear-core = "1.3.0"
wear-input = "1.1.0"

[libraries]
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
fragment = { group = "androidx.fragment", name = "fragment", version.ref = "fragment" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigation" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigation" }
preference = { group = "androidx.preference", name = "preference", version.ref = "preference" }
shapes = { group = "androidx.graphics", name = "graphics-shapes-android", version.ref = "shapes" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
wear-core = { group = "androidx.wear", name = "wear", version.ref = "wear-core" }
wear-input = { group = "androidx.wear", name = "wear-input", version.ref = "wear-input" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
navigation-safeargs = { id = "androidx.navigation.safeargs", version.ref = "navigation" }