[versions]
agp = "8.2.2"
appcompat = "1.6.1"
fragment = "1.6.2"
navigation = "2.7.7"
preference = "1.2.1"
shapes = "1.0.0-alpha05"
material = "1.12.0-alpha03"
wear-core = "1.3.0"
wear-input = "1.1.0"
wear-tooling = "1.0.0"
kotlin = "1.9.0"
play-services-wearable = "18.1.0"
compose-bom = "2024.02.01"
compose-runtime = "1.6.2"
compose-material = "1.3.0"
compose-material-icons = "1.6.2"
compose-foundation = "1.3.0"
activity-compose = "1.8.2"
core-splashscreen = "1.0.1"
constraintlayout-compose = "1.0.1"

[libraries]
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
fragment = { group = "androidx.fragment", name = "fragment", version.ref = "fragment" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigation" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigation" }
preference = { group = "androidx.preference", name = "preference", version.ref = "preference" }
shapes = { group = "androidx.graphics", name = "graphics-shapes-android", version.ref = "shapes" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
wear-core = { group = "androidx.wear", name = "wear", version.ref = "wear-core" }
wear-input = { group = "androidx.wear", name = "wear-input", version.ref = "wear-input" }
# wear
wear-tooling = { group = "androidx.wear", name = "wear-tooling-preview", version.ref = "wear-tooling" }
play-services-wearable = { group = "com.google.android.gms", name = "play-services-wearable", version.ref = "play-services-wearable" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-runtime = { group = "androidx.compose.runtime", name = "runtime-livedata", version.ref = "compose-runtime" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
compose-material = { group = "androidx.wear.compose", name = "compose-material", version.ref = "compose-material" }
compose-material-icons = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "compose-material-icons" }
compose-foundation = { group = "androidx.wear.compose", name = "compose-foundation", version.ref = "compose-foundation" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "core-splashscreen" }
constraintlayout-compose = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "constraintlayout-compose" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
navigation-safeargs = { id = "androidx.navigation.safeargs", version.ref = "navigation" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }