[versions]
agp = "8.1.1"
appcompat = "1.6.1"
fragment = "1.6.1"
navigation = "2.7.2"
preference = "1.2.1"
shapes = "1.0.0-alpha03"
material = "1.10.0-beta01"
wear = "1.3.0"
wearable = "2.9.0"

[libraries]
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
fragment = { group = "androidx.fragment", name = "fragment", version.ref = "fragment" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigation" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigation" }
preference = { group = "androidx.preference", name = "preference", version.ref = "preference" }
shapes = { group = "androidx.graphics", name = "graphics-shapes", version.ref = "shapes" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
wear = { group = "androidx.wear", name = "wear", version.ref = "wear" }
wearable-core = { group = "com.google.android.wearable", name = "wearable", version.ref = "wearable" }
wearable-support = { group = "com.google.android.support", name = "wearable", version.ref = "wearable" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
navigation-safeargs = { id = "androidx.navigation.safeargs", version.ref = "navigation" }

